feat: support auto go get default packages (#30)

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -61,4 +61,32 @@ install_golang () {
     rm -rf "${tempdir}"
 }
 
+install_default_go_pkgs() {
+  local default_go_pkgs="${HOME}/.default-golang-pkgs"
+
+  if [ ! -f $default_go_pkgs ]; then return; fi
+
+  needs_reshim=0
+
+  cat "$default_go_pkgs" | while read -r line; do
+    name=$(echo "$line" | \
+      sed 's|\(.*\) //.*$|\1|' | \
+      sed -E 's|^[[:space:]]*//.*||') # the first sed is for comments after package names, the second for full line comments
+
+    if [ -z $name ]; then continue ; fi
+    echo -ne "\nInstalling \033[33m${name}\033[39m go pkg... "
+    PATH="$ASDF_INSTALL_PATH/bin:$PATH" go get -u $name > /dev/null && rc=$? || rc=$?
+    if [[ $rc -eq 0 ]]; then
+      needs_reshim=1
+      echo -e "\033[32mSUCCESS\033[39m"
+    else
+      echo -e "\033[31mFAIL\033[39m"
+    fi
+  done
+  if [[ $needs_reshim -eq 1 ]]; then
+    "$ASDF_INSTALL_PATH/bin/asdf" reshim golang
+  fi
+}
+
 install_golang $ASDF_INSTALL_TYPE $ASDF_INSTALL_VERSION $ASDF_INSTALL_PATH
+install_default_go_pkgs
