Add `bin/download` per latest asdf guidelines (#45)
- Creates a temporary directory if using an older version of asdf.
- Install delegates to bin/download if using an older version of asdf.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -2,112 +2,65 @@
 set -eu
 [ "${BASH_VERSINFO[0]}" -ge 3 ] && set -o pipefail
 
-get_platform () {
-    local platform="$(uname | tr '[:upper:]' '[:lower:]')"
+PLUGIN_DIR="$(dirname "${BASH_SOURCE[0]}")/.."
 
-    case "$platform" in
-        linux|darwin|freebsd)
-            echo "Platform '${platform}' supported!" >&2
-            ;;
-        *)
-            echo "Platform '${platform}' not supported!" >&2
-            exit 1
-            ;;
-    esac
-
-    echo -n $platform
-}
-
-get_arch () {
-    local arch=""
-
-    case "$(uname -m)" in
-        x86_64|amd64) arch="amd64"; ;;
-        i686|i386) arch="386"; ;;
-        armv6l|armv7l) arch="armv6l"; ;;
-        aarch64|arm64) arch="arm64"; ;;
-        ppc64le) arch="ppc64le"; ;;
-        *)
-            echo "Arch '$(uname -m)' not supported!" >&2
-            exit 1
-            ;;
-    esac
-
-    echo -n $arch
-}
+# shellcheck source=/dev/null
+source "$PLUGIN_DIR/lib/helpers.sh"
 
 my_mktemp () {
     local tempdir=""
-    if [ "linux" = "$1" ] ; then
+    local platform=""
+    platform="$(get_platform)"
+
+    if [ "linux" = "$platform" ] ; then
         tempdir=$(mktemp -d asdf-golang.XXXX)
     else
         tempdir=$(mktemp -dt asdf-golang.XXXX)
     fi
-    echo -n $tempdir
-}
 
-check_shasum() {
-    local archive_file_name=$1
-    local authentic_checksum_file=$2
-    local authentic_checksum=$(cat $authentic_checksum_file)
-
-    if $(command -v sha256sum >/dev/null 2>&1); then
-        sha256sum \
-            -c <<<"$authentic_checksum $archive_file_name"
-    elif $(command -v shasum >/dev/null 2>&1); then
-        shasum \
-        -a 256 \
-        -c <<<"$authentic_checksum $archive_file_name"
-    else
-        echo "sha256sum or shasum is not available for use" >&2
-        return 1
-    fi
+    echo -n "$tempdir"
 }
 
 install_golang () {
-    local install_type=$1
-    local version=$2
-    local install_path=$3
-    local platform=$(get_platform)
-    local arch=$(get_arch)
-    local tempdir=$(my_mktemp $platform)
+    local version="$1"
+    local download_path="$2"
+    local install_path="$3"
 
-    curl "https://dl.google.com/go/go${version}.${platform}-${arch}.tar.gz" -o "${tempdir}/archive.tar.gz"
-    curl "https://dl.google.com/go/go${version}.${platform}-${arch}.tar.gz.sha256" -o "${tempdir}/archive.tar.gz.sha256"
-
-    echo 'start check sha256sum'
-    if ! check_shasum "${tempdir}/archive.tar.gz" "${tempdir}/archive.tar.gz.sha256"; then
-        echo "Authenticity of package archive can not be assured. Exiting." >&2
-        rm -rf "${tempdir}"
-        exit 1
+    if [ -z "$download_path" ] ; then
+        download_path="$(my_mktemp)"
+        ASDF_INSTALL_VERSION="$version" ASDF_DOWNLOAD_PATH="$download_path" "$PLUGIN_DIR/bin/download"
     fi
 
-    tar -C "$install_path" -xzf "${tempdir}/archive.tar.gz"
-
-    rm -rf "${tempdir}"
+    tar -C "$install_path" -xzf "${download_path}/archive.tar.gz"
 }
 
 install_default_go_pkgs() {
+  local go_path="$1/go/bin"
   local default_go_pkgs="${HOME}/.default-golang-pkgs"
 
-  if [ ! -f $default_go_pkgs ]; then return; fi
+  if [ ! -f "$default_go_pkgs" ]; then return; fi
 
-  cat "$default_go_pkgs" | while read -r line; do
+  while read -r line; do
     name=$(echo "$line" | \
       sed 's|\(.*\) //.*$|\1|' | \
       sed -E 's|^[[:space:]]*//.*||') # the first sed is for comments after package names, the second for full line comments
 
-    if [ -z $name ]; then continue ; fi
-    echo -ne "\nInstalling \033[33m${name}\033[39m go pkg... "
-    GOROOT="$ASDF_INSTALL_PATH/go" GOPATH="$ASDF_INSTALL_PATH/packages" \
-      PATH="$ASDF_INSTALL_PATH/go/bin:$PATH" go get -u $name > /dev/null && rc=$? || rc=$?
+    # Skip empty lines
+    if [ -z "$name" ]; then continue ; fi
+
+    echo -ne "\nInstalling \033[33m${name}\033[39m go pkg... " >&2
+    GOROOT="$ASDF_INSTALL_PATH/go" \
+        GOPATH="$ASDF_INSTALL_PATH/packages" \
+        PATH="$go_path:$PATH" \
+        go get -u "$name" > /dev/null && rc=$? || rc=$?
+
     if [[ $rc -eq 0 ]]; then
-      echo -e "\033[32mSUCCESS\033[39m"
+      msg "SUCCESS"
     else
-      echo -e "\033[31mFAIL\033[39m"
+      err "FAIL"
     fi
-  done
+  done < "$default_go_pkgs"
 }
 
-install_golang $ASDF_INSTALL_TYPE $ASDF_INSTALL_VERSION $ASDF_INSTALL_PATH
-install_default_go_pkgs
+install_golang "$ASDF_INSTALL_VERSION" "$ASDF_DOWNLOAD_PATH" "$ASDF_INSTALL_PATH"
+install_default_go_pkgs "$ASDF_INSTALL_PATH"
